.TH TINYPLAY 1 "October 2, 2016" "tinyplay" "TinyALSA"

.SH NAME
tinyplay \- sends audio to an audio device

.SH SYNOPSIS
.B tinyplay\fR \fIfile\fR [ \fIoptions\fR ]

.SH Description

\fBtinyplay\fR can send audio to an audio device from a wav file or standard input (as raw samples).
Options can be used to specify various hardware parameters to open the PCM with.

.SH OPTIONS

.TP
\fB\-D\fR \fIcard\fR
Card number of the PCM.
The default is 0.

.TP
\fB\-d\fR \fIdevice\fR
Device number of the PCM.
The default is 0.

.TP
\fB\-c\fR \fIchannels\fR
Number of channels the PCM will have.
This option is only valid for raw file types.
The default is 2 for raw file types.

.TP
\fB\-r\fR \fIrate\fR
Number of frames per second of the PCM.
This option is only valid for raw file types.
The default is 48000 for raw file types.

.TP
\fB\-i\fR \fIfile-type\fR
The file type used for playback.
Available types are \fIraw\fR and \fIwav\fR.
Specifying \fIraw\fR means that \fIchannels\fR, \fIrate\fR and \fIbits\fR may have to be specified as well.
The default is \fIwav\fR.

.TP
\fB\-b\fR \fIbits\fR
Number of bits per sample the PCM will have.
This option is only valid for raw file types.
The default is 16 for raw file types.

.TP
\fB\-p\fR \fIperiod_size\fR
Number of frames in a period.
The default is 1024.

.TP
\fB\-n\fR \fIperiods\fR
Number of periods the PCM will have.
The default is 4.

.SH SIGNALS

When playing audio, SIGINT will stop the playback and close the file.

.SH EXAMPLES

.TP
\fBtinyplay output.wav\fR
Plays a file called output.wav.

.TP
\fBtinyplay output.wav -D 1
Plays a file called output.wav on card 1.

.TP
\fBtinyplay output.raw -i raw --channels 2 --rate 44100 --bits 32
Plays a raw audio file called output.raw; using 2 channels, 44100 frames per second and 32 bits per sample.

.SH BUGS

Please report bugs to https://github.com/tinyalsa/tinyalsa/issues.

.SH SEE ALSO

.BR tinycap(1),
.BR tinymix(1),
.BR tinypcminfo(1)

.SH AUTHORS
Simon Wilson
.P
For a complete list of authors, visit the project page at https://github.com/tinyalsa/tinyalsa.

